[package]
name = "camwatch"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
backon.workspace = true
clap = { workspace = true, features = ["env"] }
gstreamer.workspace = true
gstreamer-app.workspace = true
gstreamer-pbutils.workspace = true
opencv.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tempfile.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
uuid.workspace = true
derive-new = "0.7.0"

[dev-dependencies]
opencv.workspace = true
testcontainers = "0.28"
