[project]
name = "cam-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mazako", email = "michal.maziarz12@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
cam-proj = "cam_proj:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
